#!/bin/bash

backup_dir=/tmp/audiobookshelf/

mkdir -p "$backup_dir"/config
mkdir -p "$backup_dir"/metadata
mkdir -p "$backup_dir"/audiobooks

# Get the pod name
pod_name=$(
  kubectl get pods -n calibre -l app=audiobookshelf -o=jsonpath='{.items[0].metadata.name}'
)

# Copy the /config directory from the pod to the local directory
kubectl cp -n calibre "$pod_name":/config "$backup_dir"/config
kubectl cp -n calibre "$pod_name":/metadata "$backup_dir"/metadata
kubectl cp -n calibre "$pod_name":/audiobooks "$backup_dir"/audiobooks
