apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
        policy-type: "app"
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000

      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:v1.11.0

          securityContext:
            allowPrivilegeEscalation: false

          ports:
            - containerPort: 9000
              protocol: TCP

          envFrom:
            - configMapRef:
                name: mealie-configmap
            - secretRef:
                name: mealie-container-env

          volumeMounts:
            - mountPath: /app/data
              name: mealie-data
            - name: secrets-store-inline
              mountPath: /mnt/secrets-store
              readOnly: true

      restartPolicy: Always
      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-data
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-kv-secrets
            nodePublishSecretRef: # Only required when using service principal mode
              name: secrets-store-creds # Only required when using service principal mode
