#!/bin/bash
# script to copy dashboards as json files to the grafana podname
# the path is the mount pount of the persistent volume defined in the helm install

podname=grafana-7d77b857c4-gdx5p

for file in ./standard-dashboards/*json; do
	kubectl cp "$file" monitoring/"$podname":/var/lib/grafana/dashboards/default
done
