{
 "title": "Home IoT",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Bedroom Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp,\n  temperature\nFROM shelly_sensor_data\nWHERE\n  device_id = 'shellyht-746CEB'\n  AND temperature IS NOT NULL\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Bedroom humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp,\n  humidity\nFROM shelly_sensor_data\nWHERE\n  device_id = 'shellyht-746CEB'\n  AND humidity IS NOT NULL\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Shelly battery level",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp,\n  battery\nFROM shelly_sensor_data\nWHERE\n  device_id = 'shellyht-746CEB'\n  AND battery IS NOT NULL\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Shelly Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{namespace=\"data\", app=\"shelly\"} | logfmt"
    }
   ]
  }
 ]
}