apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: linkding-data
  namespace: linkding
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
